[package]
name = "study_crate4"
version = "0.1.0"
authors = ["SHIINASAMA <SHIINA_KAORU@OUTLOOK.COM>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

# 依赖
[dependencies]
# 外部引用
rust-crypto = "0.2"
