[package]
name = "err1"
version = "0.1.0"
authors = ["SHIINASAMA <SHIINA_KAORU@OUTLOOK.COM>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
